# Generated by Django 4.2.3 on 2024-10-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_desc', models.CharField(max_length=255)),
                ('time', models.IntegerField(help_text='Time in minutes')),
                ('difficulty', models.CharField(max_length=50)),
                ('number_of_people', models.IntegerField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fat', models.FloatField()),
                ('ingredients', models.TextField(help_text='Comma-separated list of ingredients')),
                ('steps', models.TextField(help_text='Step-by-step cooking instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('popularity', models.IntegerField(default=0, help_text='Popularity score for sorting recipes')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('recipes', models.ManyToManyField(related_name='collections', to='recipe.recipe')),
            ],
        ),
    ]
