# Generated by Django 4.2.3 on 2024-11-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_image_url_alter_recipe_number_of_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
