# Generated by Django 4.2.3 on 2024-12-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='popularity',
            field=models.CharField(choices=[('today', 'Today'), ('week', 'Week'), ('month', 'Month'), ('none', 'None')], default='none', help_text='Период популярности рецепта', max_length=10),
        ),
    ]
