version: "3.9"

services:

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  db5:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app5:
    build: .
    volumes:
      - .:/config
      - ./static:/app/static
    ports:
    - "8005:8005"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && gunicorn config.wsgi:application -w 4 -b 0.0.0.0:8005"
    env_file:
      - .env
    depends_on:
      - db5

  celery:
    restart: always
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app5
    depends_on:
      - redis

  celery-beat:
    restart: always
    build: .
    command: celery -A config beat -l info
    volumes:
      - .:/app5
    depends_on:
      - redis

  flower:
    restart: always
    build: .
    ports:
      - 5555:5555
    command: celery -A config flower
