# Generated by Django 4.2.3 on 2023-12-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_branch_latitude_branch_longitude'),
    ]

    operations = [
       
    ]
