# Generated by Django 4.2.3 on 2024-01-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_bonus_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(null=True, upload_to='flavorize/branch/'),
        ),
    ]
